apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw2645
  labels:
    app: hw2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw2
  template:
    metadata:
      labels:
        app: hw2
    spec:
      containers:
      - name: student-survey-645
        image: asdpkp/hw2-645-repo:latestfinale
        ports:
        - containerPort: 80
  
